server:
  port: ${CUSTOM.SERVER.PORT:9790}

spring:
# Mongo Configuration
  data:
    mongodb:
      uri: mongodb://test:secret123@localhost:27017/licencia_conducir?authSource=admin

# Kafka Parameters
kafka:
  license:
    server: 127.0.0.1
    port: 9092
    topicName: license
