server:
  port: ${CUSTOM.SERVER.PORT:9080}
  
microservicio:
  security:
    key: da0abde1e4d48a440e98f5f05495a3fc31f17b2c3e9b69362f447a3bf1a35f9ebed229b9003ddbe1393fdfc29842a795

# resilience4j:
#   circuitbreaker:
#     configs:
#       product-service-cb:
#         slidingWindowSize: 12
#         failureRateThreshold: 48
#         waitDurationInOpenState: 10s
#         permittedNumberOfCallsInHalfOpenState: 8
#         slowCallRateThreshold: 58
#         slowCallDurationThreshold: 500ms
#         automaticTransitionFromOpenToHalfOpenEnabled: true
#     instances:
#       mitocode-product: 
#         base-config: product-service-cb

# Spring Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes:

        - id: license-query-service-route
          uri: lb://license-query-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/search-license/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=flag,true
        
        - id: license-command-service-route
          uri: lb://licence-command-service #http://service-1.com, http://service-2.com
          predicates:
            - Path=/api/create-license/**
          filters:
            - StripPrefix=2
            - AddRequestParameter=flag,true
        # - id: user-service-route
        #   uri: lb://user-service
        #   predicates:
        #     - Path=/api/user-service/**
        #   filters:
        #     - StripPrefix=2
        #     #- name: CustomFilter
        #     #  args:
        #     #    headerKey: MitocodeKey
        #     #    headerValue: MitocodeValue
        #     - UserServiceFilter=MitocodeKey,MitocodeValue
